# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
   push:
      branches:
         - main
      paths-ignore:
         - 'helm/**'
         - 'k8s/**'
         - 'README.md'
         -
jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Python
           uses: actions/setup-python@v4
           with:
              python-version: '3.11'

         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

         - name: Run tests
           run: |
              echo "python -m unittest discover -s tests"